project:
  type: website
  resources:
    - labs/lab-0.pdf
    - notes/sta240-01-set-theory.pdf
    - notes/sta240-02-probability-fundamentals.pdf
    - notes/sta240-03-counting.pdf
    - notes/sta240-04-conditioning.pdf
    - notes/sta240-05-rv.pdf
    - notes/sta240-06-discrete.pdf
    - notes/sta240-07-expectation.pdf
    - notes/sta240-ap-stats.pdf
    - notes/sta240-mle-1.pdf
    - notes/sta240-mle-2.pdf

website:
  page-navigation: true
  title: "STA 240 Spring 2025"
  description: "Homepage for STA 240 Probability for Statistical Inference, Modeling, and Data Analysis at Duke University, Spring 2025."
  site-url: "https://sta240-s25.github.io/"

  #repo-url: https://github.com/sta240-s25/sta240-s25.github.io/
  #repo-actions: [edit, issue]

  open-graph: true

#  draft-mode: unlinked

  sidebar:
    background: "#ffa500"
    logo: "img/logo.png"
    pinned: true
    align: center
#    tools:
#      - icon: github
#        href: https://github.com/sta199-s25
#        text: "GitHub organization"
#      - icon: code-square
#        href: https://cmgr.oit.duke.edu/containers
#        text: "RStudio containers"
#      - icon: life-preserver
#        text: Support
#        menu:
#          - icon: person-raised-hand
#            text: Office hours
#            href: https://docs.google.com/spreadsheets/d/1gXNQ9UMT01bU9qr-YDsA2GIpslldHmfwPg1gcOj2GTA/edit?usp=sharing
#          - icon: people-fill
#            text: Help from humans (Ed Discussion)
#            href: https://edstem.org/us/courses/62468/discussion/
#          - icon: robot
#            text: Help from AI (Chatbot)
#            href: https://canvas.duke.edu/courses/39994/external_tools/5887
#      - icon: file-check-fill
#        text: "Canvas"
#        menu:
#          - icon: megaphone-fill
#            text: Announcements
#            url: https://canvas.duke.edu/courses/39994/announcements
#          - icon: file-arrow-up-fill
#            text: Gradescope
#            url: https://canvas.duke.edu/courses/39994/external_tools/181
#          - icon: alphabet-uppercase
#            text: Gradebook
#            url: https://canvas.duke.edu/courses/39994/gradebook

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Syllabus"
        contents:
          - href: syllabus/syllabus_overview.qmd
            text: Overview
          - href: syllabus/syllabus_team.qmd
            text: Teaching team
          - href: syllabus/syllabus_materials.qmd
            text: Materials
          - href: syllabus/syllabus_assignments.qmd
            text: Assignments and grading
          - href: syllabus/syllabus_policies.qmd
            text: Policies
          - href: syllabus/syllabus_resources.qmd
            text: University resources
          - href: index.qmd
            text: Schedule
      - section: "Problem Sets"
        contents:
          - href: psets/pset_0.qmd
            text: Problem Set 0
          - href: psets/pset_1.qmd
            text: Problem Set 1
          - href: psets/pset_2.qmd
            text: Problem Set 2
          - href: psets/pset_3.qmd
            text: Problem Set 3
          - href: psets/pset_4.qmd
            text: Problem Set 4
          - href: psets/pset_5.qmd
            text: Problem Set 5
          - href: psets/pset_6.qmd
            text: Problem Set 6
      - section: "Labs"
        contents:
          - href: labs/lab-1.qmd
            text: Lab 1
          - href: labs/lab-2.qmd
            text: Lab 2
          - href: labs/lab-3.qmd
            text: Lab 3
          - href: labs/lab-4.qmd
            text: Lab 4
          - href: labs/lab-5.qmd
            text: Lab 5
          - href: labs/lab-6.qmd
            text: Lab 6
          - href: labs/lab-7.qmd
            text: Lab 7
          - href: labs/lab-8.qmd
            text: Lab 8
          - href: labs/lab-9.qmd
            text: Lab 9
      - section: "Exam review"
        contents:
          - href: exams/midterm-1.qmd
            text: Midterm 1
          - href: exams/midterm-2.qmd
            text: Midterm 2
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025 John Zito"
    background: "#ffa500"

format: 
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
#  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#798b93"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto

editor: visual