---
title: "Problem Set 4"
subtitle: Due Friday March 7 at 5PM
---

## Problem 0

Recommend some music for us to listen to while we grade this.

## Problem 1

Finish [Lab 4](/labs/lab-4.html)! To remind you, we were modeling insurance claims in the following way:

-   $N\sim\text{Poisson}(\lambda=100)$ is a discrete random variable counting the number of claims that an insurance company receives in a given month;
-   $X_1$, $X_2$, ... are continuous random variables representing the dollar amount of each claim;
-   $S=X_1+X_2+...+X_N$ is the total amount of money the company has to pay out. It's a new random variable that inherits its randomness from both $N$ and the $X_i$. If $S$ ends up being too large, the company will go broke.

For simplicity we assume everything is independent here, which is a totally bogus assumption. But oh well:

a.  Zoom in for a second on a single claim amount $X$ and assume $X\sim\text{Gamma}(\alpha,\,\beta)$. If we know from historical experience that claims are *typically* around \$10,000 with a standard deviation of \$2,000, what values should we pick for $\alpha$ and $\beta$ so that $X$ has the right center and spread?

b.  Simulate `n = 5000` random numbers from the gamma distribution. Plot a histogram of these numbers, and overlay a line plot of the density.

c.  Verify that the sample mean and sample variance of your random numbers are close to the prescriptions from part a. If they are not, revisit part a and adjust your choice of $\alpha$ and $\beta$ until this works.

d.  What is the probability $P(X > 15000)$? Calculate this probability exactly using the appropriate `p-` function, and also approximate it using your random numbers from part b. Verify that the two numbers are close.

e.  Write a function that simulates $S$. So your function should spit out a single number, generated in the following way:

    1.  Simulate $N$;
    2.  Given the result of Step 1, simulate independent $X_1$, $X_2$, ..., $X_N$;
    3.  Given the result of Step 2, return $S=X_1+X_2+...+X_N$.

f.  Using the function you wrote in the previous task, simulate $n=5000$ possible values for the random variable $S$ and plot a histogram of them.

g.  Use your simulations to approximate the probability $P(S>130000)$.

h.  Compute the sample mean and the sample variance of your simulations. Based on these, can you conjecture how the parameters of the underlying $\text{Poisson}(\lambda)$ and $\text{Gamma}(\alpha,\,\beta)$ distributions are related to $E(S)$ and $\text{var}(S)$? That is, propose formulas $E(S)=h(\lambda,\,\alpha,\,\beta)$ and $\text{var}(S)=g(\lambda,\,\alpha,\,\beta)$ that describe how the underlying Poisson and gamma parameters determine the moments of $S$.

## Problem 2

If $X\sim\text{Binomial}(n,\,p)$, show that

$$
E\left[\frac{1}{X+1}\right]=\frac{1-(1-p)^{n+1}}{(n+1)p}.
$$

## Problem 3

An absolutely continuous random variable $X$ has pdf

$$
f(x)=\begin{cases}
\frac{3}{22}[5 - (x-1)^2] & 1\leq x \leq3\\
0 & \text{else}.
\end{cases}
$$

a.  What is the range of $X$?
b.  Confirm that $f$ is a valid pdf.
c.  Derive the formula for the cdf of $X$ and plot it.
d.  Compute $E(X)$.
e.  Compute $\text{var}(X)$.

## Problem 4

A point is chosen at random on a line segment of length $L$. Interpret this statement, and find the probability that the ratio of the shorter to the longer segment is less than $\frac{1}{4}$.

## Problem 5

Let $X$ be any absolutely continuous random variable with pdf $f$ and cdf $F$, and assume that $E[(X-a)^2]$ and $E\left[|X-a|\right]$ are finite for all $a\in \mathbb{R}$.

a.  Compute and interpret

$$
a_0=\underset{a\in\mathbb{R}}{\arg\min}\,E[(X-a)^2].
$$

b.  Compute and interpret

$$
b_0=\underset{b\in\mathbb{R}}{\arg\min}\,E\left[|X-b|\right].
$$

## Problem 6

Consider $X\sim\textrm{Gamma}(\alpha,\,\beta)$.

a.  Find $M_X(t)=E[e^{tX}]$, the moment generating function of $X$. For what values of $t$ is it defined?
b.  Use the moment-generating function to compute $E(X)$.
c.  Use the moment-generating function to compute $\text{var}(X)$.
d.  If $c>0$, what is the distribution of $Y=cX$?
