---
title: "Extra Practice for Midterm 1"
---

On Monday February 17 during our usual class meeting, we have our first midterm exam. It will cover the following topics:

-   Set theory;
-   Probability axioms and basic rules;
-   Counting methods;
-   Conditional probability and independence;
-   Random variables in general, and discrete random variables in particular.

Below is a set of practice problems to help you prepare.

# Set theory

## Problem 1

Let $\Omega$ be the set of integers from 1 to 100, that is, $\Omega = \{1, 2, ..., 99, 100\}$. Let $E$ be the subset of $\Omega$ that contains even numbers and $C = \{1, 4, 9, 16, 25, 36, 49, 64, 81, 100\}$.

a.  List the elements in the set $E\cap C$.
b.  How many elements are in $E\cup C$?
c.  How many elements are in $(E\cap C)^c$?

## Problem 2

Take $\mathbb{R}$ to be your reference set and consider these subsets:

$$
\begin{align}
    A & = \mathbb{Z} = \{\dots,-2, -1, 0, 1, 2,\dots\}\\
    B & = (0, 1)\\
    C & = [0, \infty).
\end{align}
$$

Express the following in as simplified and concise a form as possible:

a.  $A \cap C$
b.  $B \cup C^{c}$
c.  $B^{c} \cap C$
d.  $A \cap B \cap C$

## Problem 3

Let $A$ and $B$ be two sets. Simplify the following expressions so that each set appears at most once in the final form:

a. $(A \cup B) \cap (A \cup B^{c})$
b. $(A \cup B) \cap (A^{c} \cup B) \cap (A \cup B^{c})$

# Probability axioms and basic rules

## Problem 4

Suppose that $A$ and $B$ are mutually exclusive events for which $P(A) = 0.3$ and $P(B) = 0.5$. What is the probability that...

a.  either $A$ or $B$ occurs?
b.  $A$ occurs but $B$ does not?
c.  both $A$ and $B$ occur?
d.  Are $A$ and $B$ independent? Why or why not?

## Problem 5

Out of the students in a class, 60% are geniuses, 70% love chocolate, and 40% fall into both categories. Determine the probability that a randomly selected student is neither a genius nor a chocolate lover.

## Problem 6

In the American version of the casino game roulette, the roulette wheel is divided into $38$ spaces, namely the numbers $1$ through $36$ (even numbers colored red and odd colored black) and the special single zero and double zero (both colored green). Gamblers place bets on various groups of numbers and colors. The wheel is then spun one way, a ball is set in motion the other, and the ball eventually settles on one of the numbers -- if the bet you placed included that number, you win! Let $X$ be the number on which the ball settles.

Suppose you know that the roulette wheel is not fair; in particular, you know that the probability that the ball settles on a particular zero is twice the probability the ball settles on a particular non-zero. That is to say,

$$
\mathbb{P}(X = x) = 
\begin{cases}
p & \text{if }x \in \{1, 2,\dots, 36\} \\
2p & \text{if }x \in \{0, 00\},
\end{cases}
$$
where $p \in (0, 1)$.

a. Your statistically disinclined friend says, "Oh, okay. There are $38$ possible values of $X$, so $p = \frac{1}{38}$." Explain why your friend is sorely mistaken.
b. What is the value of $p$?

# Counting methods

## Problem 7

Suppose you have a set $A$ of objects. The *power set* of $A$ is defined to be the set of all possible subsets of $A$.

a.  Let $A = \{1, 3, 5\}$. What is the power set of $A$?
b.  Suppose $A$ contains some number of items given by $N > 0$. How many sets are contained in the power set of $A$?

## Problem 8

Suppose you have your trusty standard $52$-card deck on hand, and you deal out an eight-card hand. How many possible hands have...

a. three cards of one rank, four cards of another rank, and one card of yet another rank?
b. two cards of each suit?
c. at least one ace?
d. no spades?

## Problem 9

We have now at this point the formulae for two- and three-way inclusion-exclusion, namely $$P(A \cup B) = P(A) + P(B) - P(A \cap B)$$ and $$P(A \cup B \cup C) = P(A) + P(B) + P(C) - P(A \cap B) - P(A \cap C) - P(B \cap C) + P(A \cap B \cap C).$$ Explain in counting terms why we end up subtracting the two-way intersection in the first case and adding the three-way intersection in the second case.

# Conditional probability and independence

## Problem 10

Let's talk face cards. No, not *those* face cards -- the boring kind. In a standard deck of $52$ cards, 3 (Jack, Queen, and King) of the 13 ranks are collectively known as the \`\`face cards" of the deck. Recall that a standard deck of $52$ cards also has $4$ suits (Hearts, Diamonds, Clubs, and Spades).

Suppose you deal out two cards from the deck. What is the probability that they are both face cards given that they are both hearts?

## Problem 11

Disclaimer: The referenced party gave express permission to be used in this way. All numbers quoted are self-assessments, give or take.
My Italian office mate is known to (1) watch football (in freedom units, that's soccer) on his computer monitor and (2) yell at said monitor, sometimes simultaneously. In fact, if he's watching a football match, there's a $80\%$ chance he'll be yelling at his monitor. At any rate, he only watches a match $10\%$ of the time, and he yells $40\%$ of the time that he's not watching a match.

Given that I enter my office to his excited utterances, what is the probability that he is watching a football match?

## Problem 12

Some of the greatest creations in the history of the universe have been born of mash-ups. You want breakfast and lunch? You got brunch! You want drama and comedy? You got dramedy! Perhaps the greatest mash-up of all: you want conditional probability and independent events? You got conditionally independent events!

Let $A$, $B$, and $C$ be events with $P(C) > 0$. $A$ and $B$ are *conditionally independent* given $C$ if and only if

$$
P(A \cap B \mid C) = P(A \mid C)P(B \mid C).
$$

Show that the above implies $P(A \mid B, C) = P(A \mid C)$.

# Random variables

## Problem 13

The probability that a child in a given family will inherit a certain genetic mutation is 5%, and this probability is unaffected by the inheritance status of their siblings. Consider a family with 4 children.

a.  If it is known that the first born has inherited the mutation, what is the expected number of children in the family who have inherited the mutation?
b.  If it is known that at least one child has inherited the mutation, what is the expected number of children in the family who have inherited the mutation?

## Problem 14

Two balls are chosen randomly from an urn containing $9$ green, $6$ black, and $5$ orange balls. Suppose that we win $\$2$ for each black ball selected, we lose $\$1$ for each green ball selected, and we earn nothing for each orange ball selected. Let $X$ denote our winnings.

a. Make a table listing the possible values of $X$ and the probabilities associated with each value.
b. Compute the expected value of $X$.
c. Sketch the cdf and the pmf of $X$.

## Problem 15

Suppose you have a sequence of independent $\text{Bernoulli}(p)$ trials; that is, each trial has probability $p$ of success. We are interested in seeing how long it takes to observe a fixed number $r > 0$ of successes and thus repeat the trials until we observe $r$ successes. Let $A$ be the number of the trial at which we observe the $r$th success.

a.  What is the sample space of $A$?
b.  Fix $n > 0$. What is the probability that we observe the $r$th success on the $n$th trial?

## Problem 16

Let $D \sim \text{Geometric}(p)$, and fix $n, k > 0$. What is $P(D = n + k \,|\, D > k)$? Does this look familiar?
