---
title: "Course materials"
---

## Textbooks

You are not required to purchase a textbook for this class. However, if you wish to follow along with one, these are all good options:

- `[Ross]` *A First Course in Probability* by Sheldon Ross;
- `[HTZ]` *Probability and Statistical Inference* by Robert Hogg, Elliot Tanis, and Dale Zimmerman;
- `[DS]` *Probability and Statistics* by Morris Degroot and Mark Schervish;
- `[Wass]` *All of Statistics* by Larry Wasserman.

In the "PREPARE" column of the [course schedule](https://sta240-s25.github.io/), I will indicate which parts of a book correspond to the lectures.

## Technology

This is primarily a pencil-and-paper mathematics course, and much of our work could be accomplished even if the power were out. That said, we will teach you a modicum of the `R` programming language, and you will need access to a device with internet so that you can stay up to date with the course logistics. In particular, that means:

-   [This course page](https://sta240-s25.github.io/) that you are on right now;
-   [Canvas](https://go.canvas.duke.edu/), through which you can access...
    -   Gradescope;
    -   Ed Discussion;
-   [Zoom](https://duke.zoom.us/) (e.g. for remote office hours).

If access to technology becomes a concern for you during the semester, contact the instructor immediately to discuss options.
