---
title: "Lab 2"
subtitle: Due Thursday January 30 at 11:59 PM
---

*Car Talk* (1977 - 2012) was a popular show on NPR. It featured a segment called the \`\`Puzzler,'' where the hosts would read a brain teaser and invite listeners to send in solutions for the chance to win a prize. Here is the text of one such Puzzler (original audio at around 19:19 [here](https://www.npr.org/2015/07/11/422108689/-1528-forget-the-car-find-a-convent)):

> There's a rare disease that's sweeping through your town. Of all the people who are exposed to it, 0.1% of the people actually contract the disease. There are no symptoms until the disease actually occurs. However, there's a diagnostic test that can detect the presence of the disease up to a year before it strikes. You go to your doctor, and he administers the test. It comes out positive. You say, "I'm done for!" Then you get a little bit encouraged. You say, "Wait a minute, doc, is this test 100% accurate?" Your doctor responds, "Well, not really. It's 95% accurate." In other words, 5% of the people who take the test will test positive but they don't really have the disease. **What are the chances that you actually have the disease?**

In what follows, you may find some notation useful. Let $D$ denote your true disease status, and $T$ denote the result of your test. Then

$$
\begin{align*}
    p &= P(D=+) && \text{(prevalence)}
    \\
    f_{-}&=P(T=-\,|\, D=+) && \text{(false negative rate)}
    \\
    f_{+}&=P(T=+\,|\, D=-) && \text{(false positive rate)}
    \\
    1-f_{-}&=P(T=+\,|\, D = +) && \text{(sensitivity)}
    \\
    1-f_{+}&=P(T=-\,|\, D = -) && \text{(specificity)}.
\end{align*}
$$

## Problem 1

What is your solution to the puzzler?

## Problem 2

Explain the correct way to solve this problem. Exactly what probability are we asked to compute, and what formula should we apply to do it? Does the prompt actually provide enough information to ultimately get the job done?

## Problem 3

This is the solution that the hosts ultimately revealed (original audio at around 20:30 [here](https://www.npr.org/2015/07/11/422108689/-1528-forget-the-car-find-a-convent)):

> Let's say 1000 people take the test. Fifty people will test positive and yet they will not have it. One will test positive and have it. So your chances of actually having it, even though you tested positive, are one in 51, or a little less than 2%.

So, what do you think? Did they get it right? Explain how the show interpreted the information given in the Puzzler, and explain what arithmetic formula they implicitly applied in order to compute their answer.

## Problem 4

Explain two things:

a.  Under what conditions is the formula that the show used actually an upper bound on the correct answer?
b.  Why might an upper bound on the true probability still be a useful thing to calculate?

## Problem 5

So, the show's answer, while wrong, could still be potentially useful upper bound on the true probability. Neat! But how wrong is it, even? To get a sense of this, use a computer to create some line plots of the prevalence $p\in[0,\, 1]$ against the true and approximate probabilities for different values of $f_-$ and $f_+$. Mix-and-match $f_-,\, f_+\in\{0.1,\, 0.2\}$.

## Problem 6

Now let's try to be more precise about the "wrongness" of the show's answer. Let $B$ denote the true probability, and $\overline{B}$ denote the show's approximation. In part (c) you showed that $B\leq \overline{B}$ under certain conditions. Now define

$$
\delta = \frac{\overline{B}-B}{B}.
$$

This is the relative error of the show's answer. Prove that

$$
|\delta|
\leq 
\max 
\left\{
\frac{f_-}{1-f_-} 
,\, 
\frac{f_+}{1+f_+}
\right\}
,\quad \forall p\in[0,\, 1].
$$

Interpret this result.
