---
title: "Lab 7: risk and return"
subtitle: Due Thursday April 3 at 11:59 PM
---

> My ventures are not in one bottom trusted,<br>Nor to one place; nor is my whole estate<br>Upon the fortune of this present year:<br>Therefore my merchandise makes me not sad.
>
> *The Merchant of Venice*

Mathematical finance is a major area of application for probability and statistics. When an individual or institution is deciding how best to invest their money, there are many competing options (stocks, bonds, real estate, Broadway musicals, etc), and they all bare some type of risk (EXAMPLES). The hope is that mathematical models can be used to manage this risk and guide investors in making optimal decisions in an environment of uncertainty.

In this lab, we will use tools from our course to study the *portfolio selection problem*. That is, given two competing assets, what fraction of my money should I invest in one, and what fraction should I invest in the other? Should I go 50/50? 60/40? 25/75? 100/0? The answer will hinge on two important points:

-   what does "should" mean (ie what exactly is our objective)?
-   what is the correlation between the two assets?

# Part 1 - covariance recap

If $X$ and $Y$ are jointly distributed random variables (of any type), then their **covariance** is

$$
\begin{align*}
\text{cov}(X,\,Y)
&=
E\left[(X - E(X))(Y-E(Y))\right]
\\
&=
E(XY)-E(X)E(Y)
.
\end{align*}
$$ This measures their *linear* association. Covariance can be positive, negative, or zero, indicating variables that tend to move together, tend to move apart, or tend to do their own thing, respectively. The magnitude of the covariance can be challenging to interpret, so it is useful to look at the normalized version called the **correlation**:

$$
\text{cor}(X,\,Y) = \frac{\text{cov}(X,\,Y)}{\text{sd}(X)\text{sd}(Y)}\in[-1,\,1].
$$ ADD REGRESSION PIC.

The definition of correlation gives us another way of writing the covariance which might come in handy:

$$
\text{cov}(X,\,Y) = \text{cor}(X,\,Y)\text{sd}(X)\text{sd}(Y).
$$

## Task 1

Let $(X,\,Y)$ be jointly distributed **and not necessarily independent**. If $a,\,b\in\mathbb{R}$ are constants, what is $E(aX+bY)$?

## Task 2

What is $\text{var}(aX+bY)$?

::: {.callout-warning collapse="true"}
:::

# Part 2 - modern portfolio theory

What should you do with your savings? This is a fundamental question that all grown-ups must confront at some point. If you just leave your money as cash under a mattress, inflation will eat away at its value over time, so you need to trade your cash for assets that will earn a positive real rate of return. But what should you buy? There are thousands of stocks and bonds you could choose from, not to mention paintings, crypto, NFTs, real estate, Beanie Babies, you name it. So, what are you going to buy, and in what amounts? This is called your *portfolio*.

Selecting a portfolio is hard because all of the options are fundamentally risky. If a friend proposes that you invest in a new restaurant they are opening, it is far from guaranteed that you will ever get your money back. The *return* on an asset is

$$
R
=
\frac{\text{final value} - \text{initial cost}}{\text{initial cost}}.
$$

So, how much money you made or lost compared to how much you paid. If the top is zero, you broke even. If the top is positive, you made money. If the top is negative, you lost money. As generations of luckless investors can tell you, there is a tremendous amount of random variation in asset returns, and we want to compile the "best" portfolio possible subject to this uncertainty. Maybe probability theory can help.

## A two-asset model

Imagine we live in a stylized world where there are only two assets, and we must decide what fraction of our money to invest in one, and what fraction to invest in the other. Sure, we could be talking about two stocks (Apple versus Google), or stocks versus bonds, or something fancy like that, but JZ loves Broadway musicals, so let's imagine that two producers come to my office and try to convince

*Quiet!*, a musical version of All Quiet on the Western Front

$$
R = \alpha R_1 + (1-\alpha) R_2
$$

So we know that

$$
\begin{aligned}
E(R)
&=
\alpha
\mu_1
+
(1-\alpha)
\mu_2
\\
\text{var}(R)
&=
\alpha^2\sigma_1^2+(1-\alpha)^2\sigma^2_2+2\alpha(1-\alpha)COV
\end{aligned}
$$

## Task 3

Imagine two possible portfolios:

-   Portfolio 1: I invest 50/50 in both assets;
-   Portfolio 2: I put all my money in . So 100/0.

Compute the expected return and the variance

Even though these two assets are identical, diversification decreases risk.

## Task 4

Solve for the optimal weight

minimize variance subject to

## Task 5

draw the efficient frontier

## Task 6

when you change covariance, mean returns, variance,

## Task $\infty$

This toy model was enough for one lab, but it can be extended in several directions to make it more realistic:

-   We assumed only two assets, but [the original 1952 paper](https://www.jstor.org/stable/2975974) by Harry Markowitz worked things out for a general set of $n$ assets;
-   We performed a "mean-variance" analysis that ignored all features of the return distribution besides the first and second moment. But other features matter, like the skew (third moment). If the distribution of $R_1$ is very left skewed (skewed toward the negative end, losing money) compared to $R_2$, that should surely affect the weight I place on that asset;
-   We assumed that the means and variances of asset returns were known, when in fact they are unknown and must be estimated from data, which is a major complication;
-   We assumed a static world where the decisions and their consequences are all shaking out in a single period, but the world is dynamic and decisions but be sequentially re-optimized as the environment changes;
-   We assumed the portfolio weight $w$ had to be in $[0,\,1]$, but why? Ever heard of [shorting](https://en.wikipedia.org/wiki/Short_(finance))?

If you take courses in mathematical finance, you'll learn about all of these things and much more. And you'll use a ton of probability and statistics along the way!
